FROM golang:1.22.5-alpine

LABEL maintainer="https://github.com/yongwoon"

ENV GO111MODULE=on
ENV GOPATH /go
ENV PATH=$PATH:/go/bin

RUN apk update && \
  apk add --no-cache \
  make protobuf protobuf-dev \
  bash vim openssh curl gcc g++ git musl-dev

# Install protoc-gen-go and protoc-gen-go-grpc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /go/src/github.com/yongwoon/grpc-with-go

COPY ./src /go/src/github.com/yongwoon/grpc-with-go

# Install the Go dependencies
RUN go mod tidy

RUN go mod download

# CMD ["go", "run", "main.go"]